services:
  go-admin:
    build:
      context: ./app
    depends_on:
      - db
    ports:
      - 3000:3000
    networks:
      - app
  db: 
    image: postgres:16.3
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports: 
     - 5432:5432
    networks:
      - app
networks:
  app: